{{- if and .Values.kafka_ui.ingress.enabled .Values.kafka_ui.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-kafka-ui-ingress
spec:
  ingressClassName: {{.Values.kafka_ui.ingress.className}}
  rules:
    - host: {{.Values.kafka_ui.ingress.host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-kafka-ui
                port:
                  number: 80
{{- end }}