apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kafka-ui
  labels:
    app: {{ .Release.Name }}-kafka-ui
spec:
  {{- if .Values.kafka_ui.enabled }}
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-kafka-ui
  ports:
    - port: 80
      targetPort: {{ .Values.kafka_ui.service.port }}
  {{- end }}